In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings("ignore")

In [2]:
df = sns.load_dataset("titanic")
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [3]:
def value_counts_all(df):
    for col in df.columns:
        print(f"\n Value counts for columns: '{col}'")
        print(df[col].value_counts())
        

In [4]:
value_counts_all(df)


 Value counts for columns: 'survived'
survived
0    549
1    342
Name: count, dtype: int64

 Value counts for columns: 'pclass'
pclass
3    491
1    216
2    184
Name: count, dtype: int64

 Value counts for columns: 'sex'
sex
male      577
female    314
Name: count, dtype: int64

 Value counts for columns: 'age'
age
24.00    30
22.00    27
18.00    26
28.00    25
30.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

 Value counts for columns: 'sibsp'
sibsp
0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: count, dtype: int64

 Value counts for columns: 'parch'
parch
0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: count, dtype: int64

 Value counts for columns: 'fare'
fare
8.0500     43
13.0000    42
7.8958     38
7.7500     34
26.0000    31
           ..
13.8583     1
50.4958     1
5.0000      1
9.8458      1
10.5167     1
Name: count, Length: 248, dtype: int64

 Value counts f

In [5]:
df.drop(["deck",'embark_town',"alive","class","adult_male","who"],axis=1,inplace= True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [6]:
df["age"].isnull().sum()

np.int64(177)

In [7]:
df["age"].fillna(df["age"].mean(),inplace=True)

In [8]:
df["age"].isnull().sum()

np.int64(0)

In [9]:
df.isnull().sum()

survived    0
pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    2
alone       0
dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [11]:
le = LabelEncoder()
df['sex']= le.fit_transform(df["sex"])
df["embarked"] = le.fit_transform(df["embarked"])



In [12]:

df.head()

survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         2  False
1         1       1    0  38.0      1      0  71.2833         0  False
2         1       3    0  26.0      0      0   7.9250         2   True
3         1       1    0  35.0      1      0  53.1000         2  False
4         0       3    1  35.0      0      0   8.0500         2   True

In [13]:
X = df.drop("survived",axis = 1)
y= df["survived"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2,random_state= 42)
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)



LogisticRegression()

In [14]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1])

In [15]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: survived, Length: 179, dtype: int64

In [16]:
# accuracy = model.score(X_test,y_test)
# print(accuracy)

Evaluation of model

In [17]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix
accuracy = accuracy_score(y_test,y_pred)
accuracy
precision = precision_score(y_test,y_pred)
print(precision)
recall = recall_score(y_test,y_pred)
print(recall)
confusion = confusion_matrix(y_test,y_pred)
confusion 

0.782608695652174
0.7297297297297297


array([[90, 15],
       [20, 54]])

In [18]:
from sklearn.preprocessing import StandardScaler
scaler  = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)


In [19]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors= 7)
knn_model.fit(X_train_scaled,y_train)


KNeighborsClassifier(n_neighbors=7)

In [20]:
y_pred_knn = knn_model.predict(X_test_scaled)
accuracy_score(y_test,y_pred_knn)

0.8212290502793296

In [21]:
X_train_scaled

array([[-1.61413602,  0.7243102 ,  1.22920747, ..., -0.07868358,
         0.55744438,  0.81220297],
       [-0.40055118,  0.7243102 , -0.50350514, ..., -0.37714494,
         0.55744438,  0.81220297],
       [ 0.81303367,  0.7243102 ,  0.18957991, ..., -0.47486697,
         0.55744438,  0.81220297],
       ...,
       [ 0.81303367,  0.7243102 ,  0.88266495, ..., -0.35580399,
         0.55744438, -1.23121934],
       [-1.61413602, -1.38062393, -1.19659018, ...,  1.68320121,
         0.55744438, -1.23121934],
       [-1.61413602,  0.7243102 , -0.65752403, ...,  0.86074761,
         0.55744438, -1.23121934]], shape=(712, 8))

In [22]:
from sklearn.naive_bayes import GaussianNB
model_NB = GaussianNB()
model_NB.fit(X_train,y_train)


GaussianNB()

In [23]:
y_pred_NB = model_NB.predict(X_test)
y_pred_NB

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1])

In [24]:
accuracy_score(y_test,y_pred_NB)


0.776536312849162

In [25]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       0.83      0.78      0.80       105
           1       0.71      0.77      0.74        74

    accuracy                           0.78       179
   macro avg       0.77      0.78      0.77       179
weighted avg       0.78      0.78      0.78       179



Decision Tree classifier

In [26]:
from sklearn.tree import DecisionTreeClassifier
model_DT = DecisionTreeClassifier(random_state= 42)
model_DT.fit(X_train_scaled,y_train)
y_pred_DT = model_DT.predict(X_test_scaled)
y_pred_DT

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1])

In [27]:
accuracy_score(y_test,y_pred_DT)


0.6312849162011173

In [29]:
from sklearn.svm import SVC
model_svm = SVC(kernel = 'linear')
model_svm.fit(X_train_scaled, y_train)
y_pred_svc = model_svm.predict(X_test_scaled)
print(accuracy_score(y_test,y_pred_svc))
confusion_matrix(y_test,y_pred_svc)
print(classification_report(y_test,y_pred_svc))

0.7932960893854749
              precision    recall  f1-score   support

           0       0.80      0.86      0.83       105
           1       0.78      0.70      0.74        74

    accuracy                           0.79       179
   macro avg       0.79      0.78      0.78       179
weighted avg       0.79      0.79      0.79       179

