In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
#2-D array or 2nd  order tensors
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
#3-D array
arr = np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
print(arr)
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
0
1
2
3
[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [7]:
import numpy as np
a = np.arange(15).reshape(3,5)
a.ndim
a.size
np.zeros((3,5))# 3 rows and 5 columns
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])